# On-Premise - Odoo Ansible playbook
# ==================================
#
# Serves a on-premise Odoo installation.
# Both Odoo/Python, PostgreSQL, Nginx on the same server.
#
# REQUIREMENTS
# ------------
# - Create an Ansible inventory file, which defines the host, e.g:
#   odoo ansible_ssh_host={{ HOST }} ansible_ssh_user=root
# - Put SSH keys in some path (see `odoo_user_ssh...` variables)
#
# SERVER SPECS
# ------------
# - CPU/cores: 2
# - Memory: 2 Go RAM

- name: {{ CUSTOMER_PROJECT }} - {{ ENV }} - odoo {{ VERSION }}
  hosts: {{ HOST }}
  become: yes
  roles:
    - role: anxs.postgresql
      postgresql_version: 12
      # Ubuntu focal-pgdg doesn't support architecture 'i386
      postgresql_apt_repository: "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main {{ postgresql_version }}"

      ansible_python_interpreter: python3

      postgresql_ssl: on
      # https://pgtune.leopard.in.ua
      # DB version: 12
      # OS Type: Linux
      # DB Type: Web app
      # Total Memory (RAM): 1 GB
      # Number of CPUs: 1
      # Data Storage: SSD (or SAN)
      postgresql_max_connections: 200
      postgresql_shared_buffers: 256MB
      postgresql_effective_cache_size: 768MB
      postgresql_maintenance_work_mem: 64MB
      postgresql_checkpoint_completion_target: 0.7
      postgresql_wal_buffers: 7864kB
      postgresql_default_statistics_target: 100
      postgresql_random_page_cost: 1.1
      postgresql_effective_io_concurrency: 200
      postgresql_work_mem: 655kB
      postgresql_min_wal_size: 1GB
      postgresql_max_wal_size: 4GB

    - role: ansible-odoo
      odoo_version: 13.0

      ansible_python_interpreter: python3

      #####
      # SSH
      #####
      odoo_user_generate_ssh_key: True
      odoo_user_ssh_known_hosts:
        - github.com

      #########
      # Logging
      #########
      # odoo_config_logfile: "/var/log/odoo/odoo.log"

      ############
      # PostgreSQL
      ############
      # odoo_config_db_user: odoo # default odoo
      # odoo_config_db_passwd: False # PostgreSQL peer authentication
      odoo_config_pg_path: /usr/lib/postgresql/12/bin

      ####################
      # Odoo server tuning
      ####################
      odoo_config_proxy_mode: True

      # ABOUT workers and CPU
      ################################################################
      # Worker number calculation:
      # - Rule of thumb : (#CPU * 2) + 1
      # - Cron workers need CPU
      # - 1 worker ~= 6 concurrent users
      ################################################################
      # Setup and requirements:
      # - Expects approx XX concurrent users
      # - PostreSQL on localhost (requires CPU, mem)
      ################################################################
      # Calculation:
      # - workers = (2 * 2) + 1. Use 5 to ease PostgreSQL etc
      # - 3 workers ~= 18 concurrent users
      odoo_config_workers: 3

      #####################
      # Memory (per worker)
      #####################
      # ABOUT limit_memory-soft
      # - Maximum allowed virtual memory per worker
      # - default 2048MiB (2048 * 1024 * 1024)
      # - 150% => (1.5 * 2048) * 1024 * 1024
      # odoo_config_limit_memory_soft: 3221225472

      # ABOUT limit_memory_hard
      # - Maximum allowed virtual memory per worker
      # - default 2560MiB (2560 * 1024 * 1024)
      # - 150% => (1.5 * 2560) * 1024 * 1024
      # odoo_config_limit_memory_hard: 4026531840

      ##################
      # Time CPU/request
      ##################
      # odoo_config_limit_time_cpu: 300
      # odoo_config_limit_time_real: 600

      ###########
      # Git repos
      ###########
      
      # Odoo Community
      odoo_repo_url: https://github.com/odoo/odoo.git
      odoo_repo_rev: 13.0

      # Odoo Enterprise
      # odoo_enterprise_repo_url: 
      # odoo_enterprise_repo_rev: 13.0

      # Odoo Addons
      # odoo_addons_repo_url: 
      # odoo_addons_repo_rev: 13.0
      
      odoo_config_addons_path:
        # - "{{ odoo_workdir }}/enterprise"
        # - "{{ odoo_workdir }}/addons/custom"
        - "{{ odoo_workdir }}/server/addons"

      #######################
      # packages and services
      #######################
      # odoo_addons_debian_packages:
      #   - python3-xlwt

    - role: arillso.logrotate
      logrotate_applications:
        - name: odoo
          definitions:
            - logs:
                - /var/log/odoo/odoo.log
              options:
                - rotate 10
                - daily
                - missingok
                - notifempty
