# DeltaBlue - Odoo Ansible playbook
# =================================
#
# Serves a DeltaBlue application with 2 stacks:
# 1. Python (Odoo)
# 2. PostgreSQL
#
# The Python stack is already configured to connect to PostgreSQL.
# So skip the installation PostgreSQL, hence: `odoo_install_postgresql`: False

- name: Odoo
  hosts: 127.0.0.1
  connection: local
  become: yes
  pre_tasks:
    - name: (Hack) to avoid conflict/crash on python3-serial - also installed by Odoo PypI dependencies.
      # This conflict/crash not always occurs. It depends on the host/server.
      raw: apt-get -y remove python3-serial
      changed_when: False
  roles:
    - role: cimon-io.postgresql-client
      postgresql_client_version: 12
    - role: ansible-odoo
      odoo_version: 13.0

      # SSH
      odoo_user_generate_ssh_key: True
      odoo_user_ssh_known_hosts:
        - github.com

      # PostgreSQL (on a different DeltaBlue provisioned container)
      odoo_install_postgresql: False
      odoo_config_db_host: 127.0.0.1
      # odoo_config_db_user: odoo # default odoo

      # Replaced by DeltaBlue scenario/task (DB_PASSWORD)
      # Don't change this, so search/replacement works.
      odoo_config_db_passwd: False

      # Default admin_passwd (should be replaced)        
      # odoo_config_admin_passwd: DefaultAdminPassword

      odoo_config_logfile: "/var/log/odoo/odoo.log"

      # CPU/cores: 2
      # max. workers = (2 * 2) + 1. For now 3 as safe setting.
      # Share/balance with (total) Celery workers concurrency.
      odoo_config_proxy_mode: True
      odoo_config_workers: 3

      # Odoo Community
      odoo_repo_url: https://github.com/odoo/odoo.git
      odoo_repo_rev: 13.0

      # Odoo Enterprise
      # odoo_enterprise_repo_url:
      # odoo_enterprise_repo_rev: 13.0

      # Odoo Addons
      # odoo_addons_repo_url:
      # odoo_addons_repo_rev: 13.0

      odoo_config_addons_path:
        # - "/home/{{ odoo_user }}/odoo/enterprise"
        # - "/home/{{ odoo_user }}/odoo/addons/custom"
        # - "/home/{{ odoo_user }}/odoo/addons/external"
        - "/home/{{ odoo_user }}/odoo/server/addons"
